syntax = "proto3";

package telemetry;

service TelemetryService {
    // get all idle rovers to find the best match for an order    dispatch --> telemetry 
    rpc GetIdleRovers(GetIdleRoversRequest) returns (GetIdleRoversResponse);

    // assign a delivery task to a rover 
    // return --> success to update order information and also generate otp
    //dispatch --> telemetry 
    rpc AssignTask(AssignTaskRequest) returns (AssignTaskResponse);
    // OTP and Location check 
    // telemetry  --> dispatch 
    rpc OTPValidate(OTPRequest) returns (OTPResponse);
     // Fallback  ------> if rover fail before order deleivering fall back and insert the order back into the queue with priority 1 
    // telemetry  --> dispatch 
    // partial fail after picking up  --> will handeled via controllers
    rpc OrderFallbackHandler(FallbackRequest) returns (FallbackResponse);
}

// ─── GetIdleRovers ───────────────────────────────────────

message GetIdleRoversRequest {
   
}

message RoverInfo {
    string rover_id = 1;
    double latitude = 2;
    double longitude = 3;
    string status = 4;
    float battery_level = 5;
}


message GetIdleRoversResponse {
    bool success = 1;
    repeated RoverInfo rovers = 2;
    string error = 3;
}

// ─── AssignTask ──────────────────────────────────────────

message AssignTaskRequest {
    string rover_id = 1;
    string order_id = 2;
    double order_lat = 3;
    double order_lng = 4;
}

message AssignTaskResponse {
    bool success = 1;
    string error = 2;
}


// ─── OTP Validation ──────────────────────────────────────────

message OTPRequest {
    RoverInfo rover = 1;
    string order_id = 2;
    string OTP = 3;
   
}

message OTPResponse {
    bool success = 1;
    string error = 2;
}

message FallbackRequest {
    string rover_id = 1;
    string order_id = 2;
   
}

message FallbackResponse {
    bool success = 1;
    string error = 2;
}